app:
  version: 1.0

server:
  port: 4000

spring:
  application:
    name: MakeAnOrder
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: amagi123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

